/**
 * Rank progression table — what every rank of every purchasable track costs and
 * what it demands first.
 *
 * Extracted once from "Pravidla pro ToS V12.1 (WIP).xlsx" → sheet "Dovednosti",
 * where each track's rank effects sit in columns I–X and its cost/requirement
 * line sits two rows below. THIS FILE IS HAND-MAINTAINED from here on: the
 * extraction could not resolve every clause, the gaps were filled by hand, and
 * re-running the extractor would wipe those corrections. Edit it directly.
 *
 * Track ids are "<group>.<key>", where group is the actor data path the rank is
 * written to (skills, combatSkills, weaponSkills, schools, doctrines) and key is
 * the system's own English key. `ranks` is ordered I→X; a null entry is a rank
 * the book does not sell, and a track shorter than 10 entries simply stops.
 *
 * Requirement shapes:
 *   { t: "teacher", tier }                     — needs a trainer of that tier;
 *                                                the actor's tier is GM-set
 *   { t: "attr", key, min }                    — attribute at or above min
 *   { t: "rank", group, key, min }             — a named track at or above min
 *   { t: "anyRank", group, min }               — ANY track of that group at min
 *                                                ("Doktrína III" in the book)
 *   { t: "feature", name }                     — owns the named feature item
 *   { t: "flag", key }                         — capability flag on the actor
 *   { t: "specNode", spec, node }              — specialisation node unlocked
 *   { t: "anyOf", options: [...] }             — the book's "A / B"
 *   { t: "gm", note }                          — only the GM can vouch for it
 *                                                (a special occasion, a
 *                                                language); never auto-satisfied
 *   { t: "raw", text }                         — not yet modelled; shown to the
 *                                                player verbatim, never blocks
 */

export const PROGRESSION_TRACKS = {
  "combatSkills.combat": {
    group: "combatSkills",
    key: "combat",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 2 }, { t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 6 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 8 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
    ],
  },
  "doctrines.pikeman": {
    group: "doctrines",
    key: "pikeman",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [{ t: "rank", group: "weaponSkills", key: "polearms", min: 3 }] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.swordsman": {
    group: "doctrines",
    key: "swordsman",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [{ t: "rank", group: "weaponSkills", key: "swords", min: 3 }] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.reaver": {
    group: "doctrines",
    key: "reaver",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [{ t: "anyRank", group: "weaponSkills", min: 3 }] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.shieldbearer": {
    group: "doctrines",
    key: "shieldbearer",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [{ t: "anyRank", group: "weaponSkills", min: 3 }] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.dimakerus": {
    group: "doctrines",
    key: "dimakerus",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [{ t: "anyRank", group: "weaponSkills", min: 3 }] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.duelist": {
    group: "doctrines",
    key: "duelist",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "weaponSkills", key: "swords", min: 3 }] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.monk": {
    group: "doctrines",
    key: "monk",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "weaponSkills", min: 3 }] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.rogue": {
    group: "doctrines",
    key: "rogue",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [{ t: "anyOf", options: [{ t: "anyRank", group: "weaponSkills", min: 3 }, { t: "anyRank", group: "doctrines", min: 3 }] }] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.rider": {
    group: "doctrines",
    key: "rider",
    section: "combat",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }, { t: "rank", group: "skills", key: "riding", min: 1 }] },
      { cost: 10, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 2 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }, { t: "anyRank", group: "doctrines", min: 3 }] },
      { cost: 15, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 4 }] },
      { cost: 15, currency: "sp", requires: [{ t: "teacher", tier: 2 }, { t: "rank", group: "skills", key: "riding", min: 3 }] },
      { cost: 15, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 6 }] },
      { cost: 20, currency: "sp", requires: [{ t: "teacher", tier: 2 }, { t: "anyRank", group: "doctrines", min: 7 }] },
      { cost: 20, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 8 }] },
      { cost: 20, currency: "sp", requires: [{ t: "rank", group: "skills", key: "riding", min: 5 }] },
      { cost: 25, currency: "sp", requires: [{ t: "teacher", tier: 3 }, { t: "anyRank", group: "doctrines", min: 10 }] },
    ],
  },
  "weaponSkills.swords": {
    group: "weaponSkills",
    key: "swords",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }, { t: "anyRank", group: "doctrines", min: 9 }] },
      { cost: 30, currency: "cp", requires: [] },
    ],
  },
  "weaponSkills.axes": {
    group: "weaponSkills",
    key: "axes",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }, { t: "anyRank", group: "doctrines", min: 9 }] },
      { cost: 30, currency: "cp", requires: [] },
    ],
  },
  "weaponSkills.blunt": {
    group: "weaponSkills",
    key: "blunt",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }, { t: "anyRank", group: "doctrines", min: 9 }] },
      { cost: 30, currency: "cp", requires: [] },
    ],
  },
  "weaponSkills.polearms": {
    group: "weaponSkills",
    key: "polearms",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }, { t: "anyRank", group: "doctrines", min: 9 }] },
      { cost: 30, currency: "cp", requires: [] },
    ],
  },
  "combatSkills.archery": {
    group: "combatSkills",
    key: "archery",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 2 }, { t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 6 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 8 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
    ],
  },
  "doctrines.archer": {
    group: "doctrines",
    key: "archer",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.arbalest": {
    group: "doctrines",
    key: "arbalest",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.peltast": {
    group: "doctrines",
    key: "peltast",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "weaponSkills", min: 3 }] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.juggler": {
    group: "doctrines",
    key: "juggler",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "weaponSkills", min: 3 }] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.musketeer": {
    group: "doctrines",
    key: "musketeer",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }, { t: "raw", text: "Firearms I" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "weaponSkills", min: 3 }] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [{ t: "raw", text: "Firearms III" }] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 3 }, { t: "raw", text: "Firearms V" }] },
    ],
  },
  "combatSkills.ranger": {
    group: "combatSkills",
    key: "ranger",
    section: "combat",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "specNode", spec: "ranger", node: "apprentice" }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 2 }, { t: "teacher", tier: 1 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 6 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 8 }, { t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
    ],
  },
  "doctrines.elymas": {
    group: "doctrines",
    key: "elymas",
    section: "magic",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "anyRank", group: "schools", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.incantator": {
    group: "doctrines",
    key: "incantator",
    section: "magic",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "anyRank", group: "schools", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.veneficus": {
    group: "doctrines",
    key: "veneficus",
    section: "magic",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "anyRank", group: "schools", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 0, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "doctrines.elementalist": {
    group: "doctrines",
    key: "elementalist",
    section: "magic",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "feature", name: "Familiar" }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "combatSkills.channeling": {
    group: "combatSkills",
    key: "channeling",
    section: "magic",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "flag", key: "magicPotential" }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 2 }] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
      { cost: 25, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 7 }] },
    ],
  },
  "schools.fire": {
    group: "schools",
    key: "fire",
    section: "magic",
    ranks: [
      { cost: 10, currency: "cp", requires: [{ t: "raw", text: "10/0 CP" }, { t: "rank", group: "combatSkills", key: "channeling", min: 1 }, { t: "gm", note: "specialOccasion" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 1 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 30, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 7 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 35, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 10 }, { t: "teacher", tier: 3 }] },
    ],
  },
  "schools.water": {
    group: "schools",
    key: "water",
    section: "magic",
    ranks: [
      { cost: 10, currency: "cp", requires: [{ t: "raw", text: "10/0 CP" }, { t: "rank", group: "combatSkills", key: "channeling", min: 1 }, { t: "gm", note: "specialOccasion" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 1 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 30, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 7 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 35, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 10 }, { t: "teacher", tier: 3 }] },
    ],
  },
  "schools.air": {
    group: "schools",
    key: "air",
    section: "magic",
    ranks: [
      { cost: 10, currency: "cp", requires: [{ t: "raw", text: "10/0 CP" }, { t: "rank", group: "combatSkills", key: "channeling", min: 1 }, { t: "gm", note: "specialOccasion" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 1 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 30, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 7 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 35, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 10 }, { t: "teacher", tier: 3 }] },
    ],
  },
  "schools.earth": {
    group: "schools",
    key: "earth",
    section: "magic",
    ranks: [
      { cost: 10, currency: "cp", requires: [{ t: "raw", text: "10/0 CP" }, { t: "rank", group: "combatSkills", key: "channeling", min: 1 }, { t: "gm", note: "specialOccasion" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 1 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 30, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 7 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 35, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 10 }, { t: "teacher", tier: 3 }] },
    ],
  },
  "schools.spirit": {
    group: "schools",
    key: "spirit",
    section: "magic",
    ranks: [
      { cost: 10, currency: "cp", requires: [{ t: "raw", text: "10/0 CP" }, { t: "rank", group: "combatSkills", key: "channeling", min: 1 }, { t: "gm", note: "specialOccasion" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 1 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 30, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 7 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 35, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 10 }, { t: "teacher", tier: 3 }] },
    ],
  },
  "schools.body": {
    group: "schools",
    key: "body",
    section: "magic",
    ranks: [
      { cost: 10, currency: "cp", requires: [{ t: "raw", text: "10/0 CP" }, { t: "rank", group: "combatSkills", key: "channeling", min: 1 }, { t: "gm", note: "specialOccasion" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 1 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 30, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 7 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 35, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 10 }, { t: "teacher", tier: 3 }] },
    ],
  },
  "schools.darkness": {
    group: "schools",
    key: "darkness",
    section: "magic",
    ranks: [
      { cost: 10, currency: "cp", requires: [{ t: "raw", text: "10/0 CP" }, { t: "rank", group: "combatSkills", key: "channeling", min: 1 }, { t: "gm", note: "specialOccasion" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "anyRank", group: "doctrines", min: 1 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 30, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 7 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 35, currency: "cp", requires: [{ t: "rank", group: "combatSkills", key: "channeling", min: 10 }, { t: "teacher", tier: 3 }] },
    ],
  },
  "skills.athletics": {
    group: "skills",
    key: "athletics",
    section: "str",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "str", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "str", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "str", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.smithing": {
    group: "skills",
    key: "smithing",
    section: "str",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "str", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "str", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.brawler": {
    group: "skills",
    key: "brawler",
    section: "str",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "str", min: 2 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "str", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "str", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.muscles": {
    group: "skills",
    key: "muscles",
    section: "str",
    ranks: [
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 3 }] },
      { cost: 15, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 5 }] },
      { cost: 15, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 7 }] },
      { cost: 30, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 10 }] },
    ],
  },
  "skills.acrobacy": {
    group: "skills",
    key: "acrobacy",
    section: "dex",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "dex", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "dex", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 30, currency: "sp", requires: [] },
    ],
  },
  "skills.nimbleness": {
    group: "skills",
    key: "nimbleness",
    section: "dex",
    ranks: [
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 3 }] },
      { cost: 15, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 5 }] },
      { cost: 15, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 7 }] },
      { cost: 30, currency: "sp", requires: [{ t: "anyRank", group: "doctrines", min: 10 }] },
    ],
  },
  "skills.riding": {
    group: "skills",
    key: "riding",
    section: "dex",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
    ],
  },
  "skills.pickpocketing": {
    group: "skills",
    key: "pickpocketing",
    section: "dex",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "dex", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.sailing": {
    group: "skills",
    key: "sailing",
    section: "dex",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
    ],
  },
  "skills.lockpicking": {
    group: "skills",
    key: "lockpicking",
    section: "dex",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "dex", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.stealth": {
    group: "skills",
    key: "stealth",
    section: "dex",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "dex", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.craft": {
    group: "skills",
    key: "craft",
    section: "dex",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "dex", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.dancing": {
    group: "skills",
    key: "dancing",
    section: "dex",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
    ],
  },
  "skills.drinking": {
    group: "skills",
    key: "drinking",
    section: "end",
    ranks: [
      { cost: 20, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "end", min: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "end", min: 4 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.alchemy": {
    group: "skills",
    key: "alchemy",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 4 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "int", min: 5 }, { t: "teacher", tier: 3 }] },
      { cost: 30, currency: "sp", requires: [] },
    ],
  },
  "skills.arcana": {
    group: "skills",
    key: "arcana",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 4 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 5 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.engineering": {
    group: "skills",
    key: "engineering",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 5 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.logic": {
    group: "skills",
    key: "logic",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 2 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.firstAid": {
    group: "skills",
    key: "firstAid",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 2 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.tactics": {
    group: "skills",
    key: "tactics",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 4 }, { t: "teacher", tier: 3 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 5 }, { t: "teacher", tier: 3 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.art": {
    group: "skills",
    key: "art",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 2 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.research": {
    group: "skills",
    key: "research",
    section: "int",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 4 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 5 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.deception": {
    group: "skills",
    key: "deception",
    section: "cha",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
    ],
  },
  "skills.acting": {
    group: "skills",
    key: "acting",
    section: "cha",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "cha", min: 3 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "cha", min: 4 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.music": {
    group: "skills",
    key: "music",
    section: "cha",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "cha", min: 2 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "cha", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "cha", min: 4 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.painting": {
    group: "skills",
    key: "painting",
    section: "cha",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "dex", min: 3 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.persuasion": {
    group: "skills",
    key: "persuasion",
    section: "cha",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "int", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
    ],
  },
  "skills.temptation": {
    group: "skills",
    key: "temptation",
    section: "cha",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "cha", min: 3 }, { t: "teacher", tier: 1 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
    ],
  },
  "skills.leadership": {
    group: "skills",
    key: "leadership",
    section: "cha",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "cha", min: 2 }, { t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "cha", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "cha", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "cha", min: 5 }, { t: "teacher", tier: 2 }] },
      { cost: 30, currency: "sp", requires: [] },
    ],
  },
  "skills.intimidation": {
    group: "skills",
    key: "intimidation",
    section: "cha",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
    ],
  },
  "skills.herbalism": {
    group: "skills",
    key: "herbalism",
    section: "per",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }, { t: "attr", key: "per", min: 3 }] },
    ],
  },
  "skills.traps": {
    group: "skills",
    key: "traps",
    section: "per",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "per", min: 3 }] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "per", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "skills.survival": {
    group: "skills",
    key: "survival",
    section: "per",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 20, currency: "sp", requires: [{ t: "attr", key: "per", min: 3 }] },
      { cost: 30, currency: "sp", requires: [{ t: "teacher", tier: 2 }, { t: "attr", key: "per", min: 4 }] },
    ],
  },
  "skills.insight": {
    group: "skills",
    key: "insight",
    section: "per",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 1 }, { t: "feature", name: "Talent" }] }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 2 }, { t: "feature", name: "Talent" }] }] },
    ],
  },
  "skills.animalHandling": {
    group: "skills",
    key: "animalHandling",
    section: "per",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 1 }, { t: "feature", name: "Talent" }] }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "per", min: 2 }] },
      { cost: 5, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 2 }, { t: "feature", name: "Talent" }] }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "per", min: 3 }, { t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
    ],
  },
  "doctrines.cordinas": {
    group: "doctrines",
    key: "cordinas",
    section: "wil",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "specNode", spec: "bloodSchool", node: "apprentice" }] },
      { cost: 5, currency: "cp", requires: [] },
      { cost: 5, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 15, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 20, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
    ],
  },
  "skills.dreamwalker": {
    group: "skills",
    key: "dreamwalker",
    section: "wil",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 1 }, { t: "feature", name: "Dreamer" }] }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "wil", min: 3 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "wil", min: 4 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "combatSkills.bloodManipulation": {
    group: "combatSkills",
    key: "bloodManipulation",
    section: "wil",
    ranks: [
      { cost: 5, currency: "cp", requires: [{ t: "specNode", spec: "bloodSchool", node: "apprentice" }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "cp", requires: [] },
      { cost: 15, currency: "cp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "cp", requires: [] },
      { cost: 10, currency: "cp", requires: [{ t: "teacher", tier: 3 }] },
      { cost: 25, currency: "cp", requires: [] },
    ],
  },
  "skills.meditation": {
    group: "skills",
    key: "meditation",
    section: "wil",
    ranks: [
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 20, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
    ],
  },
  "skills.mindBending": {
    group: "skills",
    key: "mindBending",
    section: "wil",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "teacher", tier: 1 }] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "wil", min: 3 }] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "wil", min: 4 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.rituals": {
    group: "skills",
    key: "rituals",
    section: "wil",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 1 }, { t: "feature", name: "Talent" }] }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [{ t: "attr", key: "wil", min: 3 }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 2 }, { t: "feature", name: "Talent" }] }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "wil", min: 4 }, { t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "attr", key: "wil", min: 5 }, { t: "teacher", tier: 3 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
  "skills.augury": {
    group: "skills",
    key: "augury",
    section: "wil",
    ranks: [
      { cost: 5, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 1 }, { t: "feature", name: "Talent" }] }] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 5, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "anyOf", options: [{ t: "teacher", tier: 2 }, { t: "feature", name: "Talent" }] }] },
      { cost: 10, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
      { cost: 10, currency: "sp", requires: [{ t: "teacher", tier: 2 }] },
      { cost: 20, currency: "sp", requires: [] },
    ],
  },
};

/** Every track id, in the order the rules sheet lists them. */
export const PROGRESSION_ORDER = Object.keys(PROGRESSION_TRACKS);

/* ===========================================================================
 * The Adept / Expert / Master feature family
 *
 * "Odbornosti" rows 193–209 price these three features generically, as
 * "*Dovednost A/B/C*: Adept" and so on, and the workbook never says which skill
 * belongs to which class. The classification below came from the GM directly
 * (2026-09-09) and exists nowhere else, so do not expect to re-derive it from
 * the rules sheet.
 *
 * These prices buy the FEATURE. They have nothing to do with what a rank of the
 * same skill costs — that is PROGRESSION_TRACKS above.
 *
 * A skill absent from this map has no valid Adept/Expert/Master feature.
 * ======================================================================== */

/** Skill key → its feature cost class. */
export const SKILL_COST_CLASSES = {
  // A
  acrobacy: "A",
  alchemy: "A", // the GM's list spells it "Alchemie", the sheet "Alchymie"
  leadership: "A",
  // B
  arcana: "B",
  athletics: "B",
  music: "B",
  dreamwalker: "B",
  pickpocketing: "B",
  smithing: "B",
  mindBending: "B",
  stealth: "B",
  firstAid: "B",
  rituals: "B",
  brawler: "B",
  augury: "B",
  research: "B",
  // C
  acting: "C",
  engineering: "C",
  logic: "C",
  painting: "C",
  lockpicking: "C",
  traps: "C",
  craft: "C",
  tactics: "C",
  art: "C",
  animalHandling: "C",
};

/**
 * Class B also covers Divinace and Transmutace, which the rules sheet lists as
 * skills but `template.json` has no key for. Add them here once they exist.
 */

/**
 * What each tier of the family costs per class, in SP, and what it demands.
 * `skillRank` is the rank of the feature's own skill; `previous` is the tier
 * below it in the same family.
 */
export const SKILL_FEATURE_TIERS = {
  adept: {
    cost: { A: 20, B: 10, C: 10 },
    skillRank: 4,
    previous: null,
  },
  expert: {
    cost: { A: 20, B: 15, C: 10 },
    skillRank: 6,
    previous: "adept",
  },
  master: {
    cost: { A: 25, B: 20, C: 15 },
    skillRank: 10,
    previous: "expert",
  },
};
